version: '3'
services:

  website:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website-web
    image: website-web
    ports:
      - 7000:80
    volumes:
      - ./web:/var/www/html/website
    links:
#      - website-db
      - website-db:dbhost
    env_file:
      - .env.db
#    networks:
#      - websitenet

  website-db:
    restart: unless-stopped
    image: mysql:5.7
    container_name: website-db
#    ports:
#      - 7306:3306
    env_file:
      - .env.db
    volumes:
      - db:/var/lib/mysql
#    networks:
#      - websitenet

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    container_name: website-phpmyadmin
    links: 
#      - db:db
      - website-db:db
    ports:
#      - 8000:80
      - 7001:80
    environment:
      MYSQL_USER: website_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 100M
#    networks:
#      - websitenet
# https://github.com/phpmyadmin/docker

  filebrowser:
    image: filebrowser/filebrowser
    container_name: website-filebrowser
    restart: unless-stopped
    volumes:
      - ./:/srv
#      - ./config.json:/config.json
#      - ./database.db:/database.db
    ports:
#      - 80:80
      - 7002:80
      - 7003:443
    environment:
#      VIRTUAL_HOST: my.virtual.host
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: my.virtual.host
      LETSENCRYPT_EMAIL: admin@my.virtual.host
# filebrowser login: admin/admin

volumes:
  web:
  db:
#networks:
#  websitenet:

# docker-compose up -d
# docker-compose down
# ----